import time, re
from src.heist_path.HeistPath import HeistPath
from src.heist_path.HeistPathA import HeistPathA


class HeistPathB(HeistPathA):
    # 全新大厅到LG1办公层线路，办公层避战部分优化
    def run_path(self):
        self.goto_lg1_skip()
        self.wait_team_ui_settle()
        # if not self.check_current_floor_str("办公"):
        #     self.check_current_floor(1)
        self.switch_to_runner(check_switched=True)
        self.lg1_wp1_safer()
        self.lg1_wp2()
        self.lg1_wp3()
        self.lg1_wp4_buster()
        self.wait_team_ui_settle()
        # if not self.check_current_floor_str("藏品"):
        #     self.check_current_floor(2)
        self.lg2_wp1_to_exit1() # self.lg2_wp1_to_exit1_safer(False)
        self.lg2_wp1_remains()
        self.lg2_wp2_to_exit2_safer()
        self.lg2_wp3_to_layzer_room()
        self.lg2_wp3_in_layzer_room()
        self.lg2_wp4()
        if self.exit_state[1]:
            self.lg2_wp4_to_exit1()
        elif self.exit_state[2]:
            self.lg2_wp4_to_exit2()
        else:
            self.lg2_wp4_to_exit3()

    # 全新大厅到LG1办公层线路，早雾控怪避战，理论最快11分00到办公层
    def goto_lg1_skip(self):
        self.log_round_info("大厅前往LG1")
        self.sleep(0.30)
        self.switch_to_runner(check_switched=True)
        self.sleep(0.10)
        self.send_key_down("w")
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key_up("w")
        self.sleep(0.20)
        self.send_key_down("d")
        self.sleep(0.57)
        self.send_key("lshift", down_time=0.32)
        self.sleep(0.57)
        self.send_key_up("d")
        self.sleep(0.20)
        self.send_key_down("w")
        self.sleep(0.40)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.60)
        self.wait_and_interact(direction="w", is_lock=True, time_out=5.2)
        self.sleep(0.10)
        self.switch_to_avoider(check_switched=True)  # 切到狗哥潜行避免碰到怪改变路径
        self.sleep(0.10)
        self.send_key_down("w")
        self.sleep(0.15)
        self.send_key_down("lshift")
        self.sleep(0.24)
        self.send_key("d", down_time=0.30)
        self.sleep(1.28)
        self.send_key_up("lshift")
        self.sleep(0.64)
        self.send_key("d", down_time=0.12)
        self.sleep(0.32)
        self.send_key("a", down_time=0.32)
        self.sleep(1.14)
        self.send_key_up("w")
        self.sleep(0.10)
        self.switch_to_fighter(check_switched=True, mode=1)  # 切到早雾控怪
        self.sleep(0.10)
        self.send_key("a", down_time=0.20)
        self.sleep(0.10)
        self.send_key_down("w")
        self.wait_and_interact(direction="w", is_lock=True, time_out=6.4)
        if self.find_interac():
            self.send_key("s", down_time=0.10)
            self.sleep(0.25)
            self.send_key_down("e")
            self.sleep(0.10)
            self.send_key_down("e")
            self.sleep(0.10)
            self.send_key("e", down_time=2.40)
            self.send_key_down("w")
            self.wait_and_interact(direction="w", is_lock=True, time_out=6.4)
        self.switch_to_avoider(check_switched=True)  # 切到狗哥潜行避免碰到怪改变路径
        self.send_key_down("w")
        self.sleep(0.32)
        self.send_key("d", down_time=0.32)
        self.sleep(0.32)
        self.send_key("a", down_time=0.32)
        self.sleep(0.32)
        self.send_key("a", down_time=0.32)
        self.sleep(0.32)
        self.send_key("a", down_time=0.16)
        self.sleep(0.42)
        self.send_key_up("w")
        self.sleep(0.10)
        self.send_key("a", down_time=3.80)
        self.sleep(0.10)
        self.send_key("a", down_time=0.10)
        self.sleep(0.10)
        self.send_key("w", down_time=0.20)
        self.sleep(0.10)
        self.send_key("w", down_time=0.10)
        self.sleep(0.10)
        self.send_key("d", down_time=0.15)
        self.sleep(0.10)
        self.send_key("d", down_time=0.15)
        self.sleep(0.10)
        self.send_key("s", down_time=0.10)
        self.sleep(0.10)
        self.send_key("s", down_time=1.14)
        self.sleep(0.10)
        self.send_key("d", down_time=0.10)
        self.sleep(0.10)
        self.send_key("d", down_time=1.60)
        self.sleep(0.10)
        self.send_key("s", down_time=0.10)
        self.sleep(0.10)
        self.send_key("s", down_time=0.10)
        self.sleep(0.20)
        self.click(0.50, 0.50, key="middle", down_time=0.15)
        self.sleep(0.30)
        self.send_key_down("w")
        self.sleep(0.20)
        self.send_key("lshift", down_time=1.25)
        self.sleep(1.80)
        self.send_key("d", down_time=0.32)
        self.sleep(0.90)
        self.send_key_down("d")
        self.sleep(0.90)
        self.send_key_up("d")
        self.send_key_up("w")
        self.switch_to_fighter(check_switched=True, mode=1)  # 切到早雾控怪
        self.sleep(0.20)
        self.send_key("s", down_time=0.10)
        self.sleep(0.20)
        self.send_key("e", down_time=2.60)
        self.sleep(0.20)
        self.send_key("w", down_time=0.22)
        self.send_key_down("w")
        self.wait_and_interact(direction="w", is_lock=True, time_out=7.64)
        if self.find_interac():
            self.clear_current_combat_spec()
            self.sleep(0.10)
            self.send_key("f", down_time=0.10)
            self.sleep(0.10)
            self.send_key("f", down_time=0.10)
            self.sleep(0.10)
            self.send_key("f", down_time=0.10)
            self.send_key_down("w")
            self.sleep(0.24)
            self.wait_and_interact(direction="w", is_lock=False, time_out=3.65)
            self.sleep(0.36)
            if not self.check_current_floor_str("大厅"):
                return
        self.send_key_down("w")
        self.sleep(0.32)
        self.send_key("a", down_time=0.28)
        self.wait_and_interact(direction="w", is_lock=False, time_out=3.65)
        self.sleep(0.30)

    # LG1部分优化
    def lg1_wp1_safer(self):
        self.log_round_info("LG1 WP1 Safer")
        self.switch_to_runner(check_switched=True) # 确认切到薄荷跑图
        self.sleep(0.20)
        self.send_key('w', down_time=9.08)
        self.sleep(0.10)
        self.send_key('d', down_time=1.72)
        self.sleep(0.10)
        self.send_key('s', down_time=1.00)
        self.sleep(0.10)
        self.send_key('f', down_time=0.10) # 这里没必要上检测，门口不安全，停太久可能会被蚊子扫
        self.sleep(0.10)
        self.send_key('f', down_time=0.10)
        self.sleep(0.20)
        self.send_key_down("f")  # start pick
        self.send_key('s', down_time=1.25)
        self.sleep(0.10)
        self.send_key_down("d")
        self.sleep(3.03)
        self.send_key_up("d")
        self.sleep(0.22)
        self.send_key_down("a")
        self.sleep(3.90)
        self.send_key_up("a")
        self.sleep(0.31)
        self.send_key_down("d")
        self.sleep(0.40)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(2.01)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(5.60)
        self.send_key_up("d")
        self.sleep(0.06)
        self.send_key_down("w")
        self.sleep(2.02)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(3.21)
        self.send_key_up("d")
        self.sleep(0.12)

    def lg1_wp4_buster(self):
        self.log_round_info("LG1 WP4 Buster")
        self.send_key_down("d")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(3.31)
        self.send_key_up("s")
        self.sleep(0.12)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.31)
        self.send_key_up("a")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(1.50)
        self.send_key_up("w")
        self.sleep(0.11)
        self.start_interaction_watch()
        self.send_key_down("f")  # start pick
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.11)
        self.send_key_up("a")
        self.sleep(1.22)
        self.stop_interaction_watch()
        self.send_key_down("w")
        self.sleep(6.58)
        self.send_key_down("d")
        self.sleep(2.62)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.31)
        self.send_key_up("a")
        self.sleep(0.32)
        self.send_key_down("w")
        self.sleep(0.21)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.31)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(1.30)
        self.start_interaction_watch()
        self.send_key_down("d")
        self.sleep(2.10)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.sleep(0.65)
        self.send_key_down("w")
        self.sleep(0.22)
        self.send_key_down("d")
        self.sleep(0.61)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.56)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.14)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.sleep(0.34)
        self.send_key_down("d")
        self.sleep(1.41)
        self.stop_interaction_watch()
        self.send_key_down("w")
        self.sleep(0.81)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(0.47)
        self.send_key_up("s")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(0.60)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(3.38)
        self.send_key_up("w")
        self.sleep(0.34)
        self.send_key_down("d")
        self.sleep(0.61)
        self.send_key_up("d")
        self.sleep(0.11)
        self.loot_safes_while_walking(direction="s", time_out=2.37)
        self.sleep(0.11)
        self.send_key_up("f")  # end pick
        self.sleep(0.10)
        self.send_key_down("d")
        self.sleep(1.33)
        self.send_key_up("d")
        self.sleep(0.12)
        self.send_key_down("w")
        self.sleep(7.70)
        self.send_key_up("w")
        self.log_round_info("LG1 WP4 Buster 开始避战路线")
        self.switch_to_avoider(check_switched=True)
        self.sleep(0.5)
        self.perform_avoidance_action()
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(6.0)
        self.send_key_up("w")
        self.switch_to_runner(check_switched=True)
        self.sleep(0.5)
        self.wait_and_interact(is_lock=True)
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(1.00)
        self.wait_and_interact(direction="w")

    # LG2部分优化
    def lg2_wp1_to_exit1_safer(self, isExit=False):
        self.log_round_info("LG2 WP1 Safer 搜刮并检测出口1状态")
        self.switch_to_runner(check_switched=True) # 换薄荷
        self.sleep(0.10)
        self.send_key('w', down_time=5.00)
        self.sleep(0.108)
        self.send_key_down('a')
        self.sleep(0.174)
        self.send_key('f', down_time=0.058)
        self.sleep(0.141)
        self.send_key('f', down_time=0.062)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.062)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.062)
        self.sleep(0.14)
        self.send_key('f', down_time=0.06)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.062)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.062)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.047)
        self.send_key_up('a')
        self.sleep(0.108)
        self.send_key('s', down_time=0.5)
        self.sleep(0.10)
        self.send_key('f', down_time=0.06)
        self.sleep(0.10)
        self.send_key_down('w')
        self.sleep(0.511)
        self.send_key('d', down_time=1.41)
        self.sleep(1.00)
        self.send_key_up('w')
        self.sleep(0.10)
        self.send_key('f', down_time=0.06)
        self.sleep(2.42)
        self.send_key('s', down_time=0.50)
        self.sleep(0.10)
        self.send_key('d', down_time=1.1)
        self.sleep(0.10)
        self.send_key_down("w")
        self.sleep(2.20)
        if isExit:
            self.walk_until_extract_panel(direction="w")
        else:
            self.exit_state[1] = self.try_open_exit(direction="w")
            # self.sleep(0.5)

    def lg2_wp2_to_exit2_safer(self):
        self.log_round_info("LG2 WP2 Safer 搜刮并检测出口2状态")
        self.send_key_down("f")  # start pick
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(1.21)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.81)
        self.send_key_up("d")
        self.sleep(0.12)
        self.send_key_up("f")  # end pick
        self.sleep(0.111)
        self.send_key('w', down_time=1.702)
        self.sleep(0.108)
        self.send_key('d', down_time=4.514)
        self.sleep(0.108)
        self.send_key('s', down_time=0.31)
        self.sleep(0.108)
        self.send_key('d', down_time=0.801)
        self.sleep(0.109)
        self.send_key('w', down_time=3.953)
        self.sleep(0.108)
        self.send_key('a', down_time=0.711)
        self.sleep(0.108)
        self.send_key('f', down_time=0.062)
        self.sleep(0.109)
        self.send_key('d', down_time=1.606)
        self.sleep(0.108)
        self.send_key('f', down_time=0.062)
        self.sleep(0.109)
        self.send_key('a', down_time=0.711)
        self.sleep(1.514)
        self.send_key('w', down_time=2.45)
        self.sleep(0.10)
        self.send_key('d', down_time=2.32)
        self.sleep(0.11)
        self.send_key_down("f")  # start pick
        self.sleep(0.10)
        self.send_key('d', down_time=0.10)
        self.sleep(0.10)
        self.send_key_down("w")
        self.sleep(4.04)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(2.87)
        self.send_key_up("s")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(1.51)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("f")  # end pick
        self.sleep(0.11)
        self.switch_to_runner()
        self.sleep(0.28)
        self.send_key_down("w")
        self.sleep(3.65)
        self.exit_state[2] = self.try_open_exit(direction="w")
        self.sleep(0.40)

    # 尝试兼容1600*900分辨率
    def check_current_floor_str(self, floor_str):
        ret = self.wait_ocr(0.04, 0.23, 0.17, 0.28, match=re.compile(floor_str), time_out=5)
        if ret:
            return True
    
    # 定制化战斗切人方法
    def switch_to_fighter(self, check_switched=False, mode="all_desc"):
        """切换到可用战斗角色。   
        `mode` 调度策略（配置重新从小到大排序后）：
        - "all_desc": [默认]按键位从大到小完整尝试（如 ["4", "1"]）
        - "all_asc" : 按键位从小到大完整尝试（如 ["1", "4"]）
        -     1     : 只切当前最小的那个键位
        -    -1     : 只切当前最大的那个键位
        -     n     : 只切重新排序后的【第 n 个】角色
        """
        config_keys = list(self.config.get(self.CONF_FIGHTER, []))
        if not config_keys:
            dead_keys = set(self._dead_fighter_keys)
            config_keys = [item for item in config_keys if item not in dead_keys]
            return self._begin_character_switch(self.ROLE_FIGHTER, config_keys, check_switched)
        sorted_keys = sorted(config_keys, key=int)
        if mode == "all_asc":
            keys = sorted_keys
        elif mode == "all_desc":
            keys = sorted_keys[::-1]
        elif isinstance(mode, int):   
            if mode == -1:
                keys = [sorted_keys[-1]]
            else:
                idx = mode - 1
                if 0 <= idx < len(sorted_keys):
                    keys = [sorted_keys[idx]]
                else:
                    self.log_error(f"切人位置越界！配置排序后只有 {len(sorted_keys)} 个人，你请求切第 {mode} 个，自动切最后一个。")
                    keys = [sorted_keys[-1]]
        else:
            keys = sorted_keys[::-1]
        dead_keys = set(self._dead_fighter_keys)
        keys = [item for item in keys if item not in dead_keys]
        return self._begin_character_switch(self.ROLE_FIGHTER, keys, check_switched)
    
    def clear_current_combat_spec(self):
        """处理并等待当前小战斗结束。

        会切到战斗角色、攻击直到红色血条消失，再切回跑图角色。
        若战斗超时或所有战斗角色不可用会中断路径。
        """
        _key = self.switch_to_fighter(check_switched=True, mode="all_desc")
        self.wait_until(self.has_health_bar)
        deadline = time.time() + 60
        settle = -1
        in_team_settle = -1
        while time.time() < deadline:
            self.send_key_down("space")
            self.sleep(0.05)
            self.mouse_down()
            self.sleep(0.05)
            self.send_key_up("space")
            self.sleep(0.05)
            self.mouse_up()
            self.sleep(0.45)
            if not self.is_in_team():
                if in_team_settle < 0:
                    in_team_settle = time.time()
                if time.time() - in_team_settle > 1:
                    self.log_info(f"fighter {_key} dead, try next")
                    self._dead_fighter_keys.append(_key)
                    self.ensure_in_team()
                    _key = self.switch_to_fighter()
            else:
                in_team_settle = -1
                _key = self._current_fighter_key or _key
            self.send_key_down(_key)
            self.sleep(0.02)
            self.send_key_up(_key)
            self.next_frame()
            if not self._find_red_health_bar(10):
                if settle < 0:
                    settle = time.time()
                if time.time() - settle > 2:
                    break
            else:
                settle = -1
        else:
            raise AbortException("timeout for clear_current_combat")
        self.switch_to_runner(check_switched=True)
