import time, re
from src.heist_path.HeistPath import HeistPath
from src.heist_path.HeistPathA import HeistPathA


class HeistPathB(HeistPathA):
    # 全新大厅到LG1办公层线路，办公层避战部分优化
    def run_path(self):
        self.goto_lg1_skip()
        self.wait_team_ui_settle()
        self.check_current_floor(1)
        self.switch_to_runner(check_switched=True)
        self.lg1_wp1_safer()
        self.lg1_wp2()
        self.lg1_wp3()
        self.lg1_wp4_buster()
        self.wait_team_ui_settle()
        if not self.check_current_floor_str("藏品"):
            self.check_current_floor(2)
        self.lg2_wp1_to_exit1() # self.lg2_wp1_to_exit1_safer(False)
        self.lg2_wp1_remains()
        self.lg2_wp2_to_exit2_safer()
        self.lg2_wp3_to_layzer_room()
        self.lg2_wp3_in_layzer_room()
        self.lg2_wp4()
        if self.exit_state[1]:
            self.lg2_wp4_to_exit1()
        elif self.exit_state[2]:
            self.lg2_wp4_to_exit2()
        else:
            self.lg2_wp4_to_exit3()

    # 全新大厅到LG1办公层线路，早雾控怪避战，理论最快11分00到办公层
    def goto_lg1_skip(self):
        self.log_round_info("寻路到LG1")
        self.sleep(0.30)
        self.switch_to_runner(check_switched=True)
        self.sleep(0.10)
        self.send_key_down("w")
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.42)
        self.send_key_up("w")
        self.sleep(0.20)
        self.send_key_down("d")
        self.sleep(0.57)
        self.send_key("lshift", down_time=0.32)
        self.sleep(0.57)
        self.send_key_up("d")
        self.sleep(0.20)
        self.send_key_down("w")
        self.sleep(0.40)
        self.send_key("lshift", down_time=0.25)
        self.sleep(0.60)
        self.wait_and_interact(direction="w", is_lock=True, time_out=5.2)
        self.sleep(0.10)
        self.switch_to_avoider(check_switched=True)  # 切到狗哥潜行避免碰到怪改变路径
        self.sleep(0.10)
        self.send_key_down("w")
        self.sleep(0.15)
        self.send_key_down("lshift")
        self.sleep(0.24)
        self.send_key("d", down_time=0.30)
        self.sleep(1.28)
        self.send_key_up("lshift")
        self.sleep(0.64)
        self.send_key("d", down_time=0.12)
        self.sleep(0.32)
        self.send_key("a", down_time=0.32)
        self.sleep(1.14)
        self.send_key_up("w")
        self.sleep(0.10)
        self.switch_to_fighter(check_switched=True)  # 切到早雾控怪
        self.sleep(0.10)
        self.send_key("a", down_time=0.20)
        self.sleep(0.10)
        self.send_key_down("w")
        self.wait_and_interact(direction="w", is_lock=True, time_out=6.4)
        if self.find_interac():
            self.send_key("s", down_time=0.10)
            self.sleep(0.25)
            self.send_key_down("e")
            self.sleep(0.10)
            self.send_key_down("e")
            self.sleep(0.10)
            self.send_key("e", down_time=2.40)
            self.send_key_down("w")
            self.wait_and_interact(direction="w", is_lock=True, time_out=6.4)
        self.switch_to_avoider(check_switched=True)  # 切到狗哥潜行避免碰到怪改变路径
        self.send_key_down("w")
        self.sleep(0.32)
        self.send_key("d", down_time=0.32)
        self.sleep(0.32)
        self.send_key("a", down_time=0.40)
        self.sleep(0.20)
        self.send_key("a", down_time=0.32)
        self.sleep(0.52)
        self.send_key_up("w")
        self.sleep(0.10)
        self.send_key("a", down_time=3.80)
        self.sleep(0.10)
        self.send_key("a", down_time=0.10)
        self.sleep(0.10)
        self.send_key("w", down_time=0.20)
        self.sleep(0.10)
        self.send_key("w", down_time=0.10)
        self.sleep(0.10)
        self.send_key("d", down_time=0.15)
        self.sleep(0.10)
        self.send_key("d", down_time=0.15)
        self.sleep(0.10)
        self.send_key("s", down_time=0.10)
        self.sleep(0.10)
        self.send_key("s", down_time=1.14)
        self.sleep(0.10)
        self.send_key("d", down_time=0.10)
        self.sleep(0.10)
        self.send_key("d", down_time=1.60)
        self.sleep(0.10)
        self.send_key("s", down_time=0.10)
        self.sleep(0.10)
        self.send_key("s", down_time=0.10)
        self.sleep(0.20)
        self.click(0.50, 0.50, key="middle", down_time=0.15)
        self.sleep(0.30)
        self.send_key_down("w")
        self.sleep(0.20)
        self.send_key("lshift", down_time=1.25)
        self.sleep(1.80)
        self.send_key("d", down_time=0.32)
        self.sleep(0.90)
        self.send_key_down("d")
        self.sleep(0.90)
        self.send_key_up("d")
        self.send_key_up("w")
        self.switch_to_fighter(check_switched=True)  # 切到早雾控怪
        self.sleep(0.20)
        self.send_key("s", down_time=0.10)
        self.sleep(0.20)
        self.send_key("e", down_time=2.60)
        self.sleep(0.20)
        self.send_key("w", down_time=0.22)
        self.send_key_down("w")
        self.wait_and_interact(direction="w", is_lock=True, time_out=7.64)
        if self.find_interac():
            self.goto_lg1_interrupted()
        self.send_key_down("w")
        self.sleep(0.32)
        self.send_key("a", down_time=0.28)
        self.wait_and_interact(direction="w", is_lock=False, time_out=3.65)
        self.sleep(0.30)

    # LG1部分优化
    def lg1_wp1_safer(self):
        self.switch_to_runner(check_switched=True) # 确认切到薄荷跑图
        self.sleep(0.20)
        self.send_key('w', down_time=9.08)
        self.sleep(0.10)
        self.send_key('d', down_time=1.72)
        self.sleep(0.10)
        self.send_key('s', down_time=1.00)
        self.sleep(0.10)
        self.send_key('f', down_time=0.10) # 这里没必要上检测，门口不安全，停太久可能会被蚊子扫
        self.sleep(0.10)
        self.send_key('f', down_time=0.10)
        self.sleep(0.20)
        self.send_key_down("f")  # start pick
        self.send_key('s', down_time=1.25)
        self.sleep(0.10)
        self.send_key_down("d")
        self.sleep(3.03)
        self.send_key_up("d")
        self.sleep(0.22)
        self.send_key_down("a")
        self.sleep(3.90)
        self.send_key_up("a")
        self.sleep(0.31)
        self.send_key_down("d")
        self.sleep(0.40)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(2.01)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(5.60)
        self.send_key_up("d")
        self.sleep(0.06)
        self.send_key_down("w")
        self.sleep(2.02)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(3.21)
        self.send_key_up("d")
        self.sleep(0.12)

    def lg1_wp4_buster(self):
        self.send_key_down("d")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(3.31)
        self.send_key_up("s")
        self.sleep(0.12)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.31)
        self.send_key_up("a")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(1.50)
        self.send_key_up("w")
        self.sleep(0.11)
        self.start_interaction_watch()
        self.send_key_down("f")  # start pick
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.11)
        self.send_key_up("a")
        self.sleep(1.22)
        self.stop_interaction_watch()
        self.send_key_down("w")
        self.sleep(6.58)
        self.send_key_down("d")
        self.sleep(2.62)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("a")
        self.sleep(0.31)
        self.send_key_up("a")
        self.sleep(0.32)
        self.send_key_down("w")
        self.sleep(0.21)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.31)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(1.30)
        self.start_interaction_watch()
        self.send_key_down("d")
        self.sleep(2.10)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.sleep(0.65)
        self.send_key_down("w")
        self.sleep(0.22)
        self.send_key_down("d")
        self.sleep(0.61)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.56)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.14)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("w")
        self.sleep(0.34)
        self.send_key_down("d")
        self.sleep(1.41)
        self.stop_interaction_watch()
        self.send_key_down("w")
        self.sleep(0.81)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(0.47)
        self.send_key_up("s")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(0.60)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(3.38)
        self.send_key_up("w")
        self.sleep(0.34)
        self.send_key_down("d")
        self.sleep(0.61)
        self.send_key_up("d")
        self.sleep(0.11)
        self.loot_safes_while_walking(direction="s", time_out=2.37)
        self.sleep(0.11)
        self.send_key_up("f")  # end pick
        self.sleep(0.10)
        self.send_key_down("d")
        self.sleep(1.33)
        self.send_key_up("d")
        self.sleep(0.12)
        self.send_key_down("w")
        self.sleep(7.70)
        self.send_key_up("w")
        self.switch_to_avoider(check_switched=True)
        self.sleep(0.5)
        self.perform_avoidance_action()
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(6.0)
        self.send_key_up("w")
        self.switch_to_runner(check_switched=True)
        self.sleep(0.5)
        self.wait_and_interact(is_lock=True)
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(1.00)
        self.wait_and_interact(direction="w")

    # LG2部分优化
    def lg2_wp1_to_exit1_safer(self, isExit=False):
        self.switch_to_runner(check_switched=True) # 换薄荷
        self.sleep(0.10)
        self.send_key('w', down_time=5.00)
        self.sleep(0.108)
        self.send_key_down('a')
        self.sleep(0.174)
        self.send_key('f', down_time=0.058)
        self.sleep(0.141)
        self.send_key('f', down_time=0.062)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.062)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.062)
        self.sleep(0.14)
        self.send_key('f', down_time=0.06)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.139)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.062)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.062)
        self.sleep(0.139)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.06)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.141)
        self.send_key('f', down_time=0.061)
        self.sleep(0.14)
        self.send_key('f', down_time=0.061)
        self.sleep(0.047)
        self.send_key_up('a')
        self.sleep(0.108)
        self.send_key('s', down_time=0.5)
        self.sleep(0.10)
        self.send_key('f', down_time=0.06)
        self.sleep(0.10)
        self.send_key_down('w')
        self.sleep(0.511)
        self.send_key('d', down_time=1.41)
        self.sleep(1.00)
        self.send_key_up('w')
        self.sleep(0.10)
        self.send_key('f', down_time=0.06)
        self.sleep(2.42)
        self.send_key('s', down_time=0.50)
        self.sleep(0.10)
        self.send_key('d', down_time=1.1)
        self.sleep(0.10)
        self.send_key_down("w")
        self.sleep(2.20)
        if isExit:
            self.walk_until_extract_panel(direction="w")
        else:
            self.exit_state[1] = self.try_open_exit(direction="w")
            # self.sleep(0.5)

    def lg2_wp2_to_exit2_safer(self):
        self.send_key_down("f")  # start pick
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(1.21)
        self.send_key_down("space")
        self.sleep(0.06)
        self.send_key_up("space")
        self.sleep(0.81)
        self.send_key_up("d")
        self.sleep(0.12)
        self.send_key_up("f")  # end pick
        self.sleep(0.111)
        self.send_key('w', down_time=1.702)
        self.sleep(0.108)
        self.send_key('d', down_time=4.514)
        self.sleep(0.108)
        self.send_key('s', down_time=0.31)
        self.sleep(0.108)
        self.send_key('d', down_time=0.801)
        self.sleep(0.109)
        self.send_key('w', down_time=3.953)
        self.sleep(0.108)
        self.send_key('a', down_time=0.711)
        self.send_key_down("f")  # start pick
        self.sleep(0.31)
        self.send_key_down("d")
        self.sleep(1.61)
        self.send_key_up("d")
        self.sleep(0.30)
        self.send_key_down("a")
        self.sleep(0.72)
        self.send_key_up("a")
        self.sleep(0.26)
        self.send_key_down("w")
        self.sleep(2.60)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(2.31)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_down("w")
        self.sleep(4.03)
        self.send_key_up("w")
        self.sleep(0.11)
        self.send_key_down("s")
        self.sleep(2.87)
        self.send_key_up("s")
        self.sleep(0.11)
        self.send_key_down("d")
        self.sleep(1.51)
        self.send_key_up("d")
        self.sleep(0.11)
        self.send_key_up("f")  # end pick
        self.sleep(0.11)
        self.switch_to_runner()
        self.sleep(0.28)
        self.send_key_down("w")
        self.sleep(2.56)
        self.send_key_down("a")
        self.sleep(0.30)
        self.send_key_up("a")
        self.sleep(1.57)
        self.exit_state[2] = self.try_open_exit(direction="w")
        self.sleep(0.40)

    # 尝试兼容1600*900分辨率
    def check_current_floor_str(self, str):
        ret = self.wait_ocr(0.04, 0.23, 0.17, 0.28, match=re.compile(str), time_out=10)
        if ret:
            return True